/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package VisiteurVsCaseOf;
import io.github.ljuglaret.visiteur.*;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
   @Test void testPlus() {
        ExpressionAVisiter e1 = new Plus(new Constante(2),new Constante(3));
        ExpressionAVisiter e2 = new Plus(new Constante(3),new Constante(2));
        ExpressionAVisiter e3 = new Plus( new Plus(new Constante(2),new Constante(3)),new Constante(4));
        ExpressionAVisiter e4 = new Plus(new Constante(2),new Plus(new Constante(3),new Constante(4)));

        VisiteurCalculReel eval = new VisiteurCalculReel(); 

        //Commutativité : a+b = b+a
        assertEquals(e1.accept(eval),e2.accept(eval));
        assertEquals(5.0, e1.accept(eval));
        
        //associativité : (a+b)+c = a+(b+c)
        assertEquals(e3.accept(eval),e4.accept(eval));
        assertEquals(9.0, e3.accept(eval));
    }

    @Test void testProduit() {
        ExpressionAVisiter e1 = new Prod(new Constante(2),new Constante(3));
        ExpressionAVisiter e2 = new Prod(new Constante(3),new Constante(2));
        ExpressionAVisiter e3 = new Prod(new Prod(new Constante(2),new Constante(3)),new Constante(4));
        ExpressionAVisiter e4 = new Prod(new Constante(2),new Prod(new Constante(3),new Constante(4)));

        VisiteurCalculReel eval = new VisiteurCalculReel(); 

        //Commutativité : a*b = b*a
        assertEquals(e1.accept(eval),e2.accept(eval));
        assertEquals(6.0,e1.accept(eval));
        
        //associativité : (a*b)*c = a*(b*c)
        assertEquals(e3.accept(eval),e4.accept(eval));
        assertEquals(24.0, e3.accept(eval));
    }
}
