/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package io.github.ljuglaret.visiteur;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void testPlus() {
        Expr e1 = new Plus(new Constante(2),new Constante(3));
        Expr e2 = new Plus(new Constante(3),new Constante(2));
        Expr e3 = new Plus( new Plus(new Constante(2),new Constante(3)),new Constante(4));
        Expr e4 = new Plus(new Constante(2),new Plus(new Constante(3),new Constante(4)));

        //Commutativité : a+b = b+a
        assertEquals(new VisiteurOperation(e1).calcul(),new VisiteurOperation(e2).calcul());
        assertEquals(5.0, new VisiteurOperation(e1).calcul());
        
        //associativité : (a+b)+c = a+(b+c)
        assertEquals(new VisiteurOperation(e3).calcul(),new VisiteurOperation(e4).calcul());
        assertEquals(9.0, new VisiteurOperation(e3).calcul());
    }

    @Test void testProduit() {
        Expr e1 = new Prod(new Constante(2),new Constante(3));
        Expr e2 = new Prod(new Constante(3),new Constante(2));
        Expr e3 = new Prod(new Prod(new Constante(2),new Constante(3)),new Constante(4));
        Expr e4 = new Prod(new Constante(2),new Prod(new Constante(3),new Constante(4)));

        //Commutativité : a*b = b*a
        assertEquals(new VisiteurOperation(e1).calcul(),new VisiteurOperation(e2).calcul());
        assertEquals(6.0, new VisiteurOperation(e1).calcul());
        
        //associativité : (a*b)*c = a*(b*c)
        assertEquals(new VisiteurOperation(e3).calcul(),new VisiteurOperation(e4).calcul());
        assertEquals(24.0, new VisiteurOperation(e3).calcul());
    }
}
